version: '1.0'
services:
  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter
  mongo:
    image: mongo:latest
  server:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts

  nginx:
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - ../..:/workspaces:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf